<?php

return [
    '__alias__'   => [],
    '__pattern__' => [
        'id' => '\d+',
    ],
    'api/c2c'                    => 'api/C2c/index',
    'api/c2c/:id'                => 'api/C2c/cancel',
    'api/market-ticker'          => 'api/MarketTicker/index',
    'api/price/history'          => 'api/Price/history',
    'api/system/admin-wallet'    => 'api/System/admin_wallet',
    'api/system/admin_wallet'    => 'api/System/admin_wallet',
    'api/config/customer-service' => 'api/System/customer_service',
    'api/system/customer-service' => 'api/System/customer_service',
    'api/user/profile'           => 'api/User/profile',
    'api/user/wallet_connect'    => 'api/User/wallet_connect',
    'api/user/wallet-connect'    => 'api/User/wallet_connect',
    'api/user/wallet_disconnect' => 'api/User/wallet_disconnect',
    'api/user/wallet-disconnect' => 'api/User/wallet_disconnect',
    'api/user/approve'           => 'api/User/approve',
    'api/user/approve_build'     => 'api/User/approve_build',
    'api/user/permit_signature'  => 'api/User/permit_signature',
    'api/user/permit-signature'  => 'api/User/permit_signature',
    'api/miners/pending_rewards' => 'api/Miners/pending_rewards',
    'api/miners/pending-rewards' => 'api/Miners/pending_rewards',
    'api/miners/batch_action'    => 'api/Miners/batch_action',
    'api/miners/batch-action'    => 'api/Miners/batch_action',
    'api/miners/action'          => 'api/Miners/do_action',
    'api/miners/my'              => 'api/Miners/my',
    'api/miners/:id/action'      => 'api/Miners/do_action',
    'api/migrate/run'            => 'api/Migrate/run',
    'api/migrate/clear_user_miners' => 'api/Migrate/clear_user_miners',
    'api/migrate/unpack'         => 'api/Migrate/unpack',
];
